version: "1.0"


services:
  db:
    container_name: announcement_db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: eddy
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
    networks:
      announcement_net:
        ipv4_address: 172.18.0.2

  redis:
    container_name: announcement_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      announcement_net:
        ipv4_address: 172.18.0.3

  announcement:
    image: announcement
    container_name: announcement_app
    ports:
      - "8080:8080"
    environment:
      MARIADB_HOST: 172.18.0.2
      REDIS_HOST: 172.18.0.3
    networks:
      announcement_net:
        ipv4_address: 172.18.0.4

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./docker/scripts:/scripts
    environment:
      - K6_PROMETHEUS_PUSH_INTERVAL=1s # Prometheus 데이터 푸시 주기
#    command: ["run", "--out", "experimental-prometheus-rw=http://172.18.0.6:9090/api/v1/write", "/scripts/loadtest.js"]
    command: ["run", "--out", "influxdb=http://172.18.0.6:8086/k6", "/scripts/loadtest.js"]
    networks:
      announcement_net:
        ipv4_address: 172.18.0.5
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      announcement_net:
        ipv4_address: 172.18.0.6
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
      INFLUXDB_USER: k6
      INFLUXDB_USER_PASSWORD: k6password

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      announcement_net:
        ipv4_address: 172.18.0.7
    depends_on:
      - influxdb

networks:
  announcement_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

