server:
  port: 8080

spring:
  application:
    name: announcement
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    initialize: false
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST:localhost}:3306/announcement?serverTimezone=asia/seoul&characterEncoding=UTF-8
    username: ${MARIADB_USERNAME:root}
    password: ${MARIADB_ROOT_PASSWORD:eddy}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect